### ISSUE TITLE
No order items 

### ISSUE THREAD

**Issue by bartpijn** [awesto/cookiecutter-django-shop#27]
## What happened?
After creating an order with some items, the ordered items are not visible on the 'change order' admin page (admin/my-shop/order/**x**/change/) under the Ordered Items header. The customer, however, can see their just bought items. 

## What should've happened instead?
Ordered items should be visible on the 'change order' page.

## Steps to reproduce

1. Place an order, pay it upfront
2. open admin -> orders -> _corresponding order_

**Comment by jrief** [comment]
As a first fix, remove the line 76 in `shop.admin.order.py` starting with
`template = 'shop/admin/edit_inline/stacked-order.html'`.

**Comment by bartpijn** [comment]
> As a first fix, remove the line 76 in shop.admin.order.py starting with
> template = 'shop/admin/edit_inline/stacked-order.html'.

This improved it, now the product code, unit price and ordered quantity are visible. Thanks!

**Comment by jrief** [comment]
This has been fixed now in the HEAD of django-shop master branch.
Please recheck, so that I can bundle a new release.
