### ISSUE TITLE
initialize_shop_demo.py looks for shop_paypal and compressor

### ISSUE THREAD

**Issue by pdbethke** [awesto/cookiecutter-django-shop#5]
Ubuntu 18.04

Installing the demo using the defaults of [n] to paypal and compressor will trigger an error when executing pipenv run ./manage.py initialize_shop_demo. For example:

choosing the default use_compressor [n]: 
Will result in:
/project-name/my-shop/myshop/management/commands/initialize_shop_demo.py", line 37, in clear_compressor_cache
    from compressor.conf import settings
ModuleNotFoundError: No module named 'compressor'

Presumably because the init demo script expects these modules to be installed regardless.

**Comment by jrief** [comment]
Thanks for reporting. This has been fixed now.
